# Extract Prodcom data

**Related publication**

 - Title: Residual biomass to bio-based chemicals and plastics: ex-ante screening methodology for prioritizing high-impact substitutions
 - Authors: [Nicolas LIENART](https://orcid.org/0009-0001-3259-2819), [Thibaut LECOMPTE](https://orcid.org/0000-0001-9237-8454), [Lorie HAMELIN](https://orcid.org/0000-0001-9092-1900) 
 - Journal: Resources, Conservation and Recycling (RCR) - Elsevier
 - Doi: #todo
 - Git repository (Forge INRAE): https://forge.inrae.fr/nicolas.lienart/screen-lca-paper-supplementary-code
 - Git repository (GitHub): https://github.com/nicolnt/screen-lca-paper-supplementary-code

**Description and details**

This code extracts relevant products data from the Eurostat Prodcom database. Refer to the aforementioned main manuscript and accompanying supplementary information documents for more details.

**Updates**
 
 - May 04, 2026: Ready for submission

**Package versions**

 - See [`environment.yml`](./environment.yml)

**Relevant references**

 - Eurostat (2023) “Statistical Classification of Economic Activities in the European Community, Rev. 2.1 (NACE Rev. 2.1).” Available at: https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2.1._(NACE_2.1).
 - Eurostat (2026) “PRODCOM. Statistics by products. Sold production, exports and imports (ds-059358).” Available at: https://ec.europa.eu/eurostat/databrowser/product/view/ds-059358?category=prom.
 - Eurostat (2025) “Database - Prodcom.” Available at: https://ec.europa.eu/eurostat/web/prodcom/database.
 - Eurostat (2023) European business statistics user’s manual for PRODCOM: 2023 edition. 2023 edition. LU: Publications Office. Available at: https://data.europa.eu/doi/10.2785/39767 (Accessed: May 15, 2024).
 - Eurostat (2025) Quick guide to accessing PRODCOM data in the Eurostat’s Data Browser DS-059358. Available at: https://ec.europa.eu/eurostat/documents/120432/19597181/Quick+guide+on+accessing+PRODCOM+data+DS-059358.pdf.

In [2]:
import pandas as pd
import numpy as np

In [7]:
from importlib.metadata import version
print('pandas:', version('pandas'))
print('openpyxl:', version('openpyxl'))

pandas: 2.2.3
openpyxl: 3.1.5

In [2]:
# NOTE: Repository link: https://ec.europa.eu/eurostat/databrowser/bulk?lang=en&alphabeticalFilter=D&searchFilter=DS
# NOTE: Took <10s
input_df = pd.read_csv('Prodcom_data/estat_ds-059358.tsv', sep='\t')
input_df

,"freq,reporter,product,indicators\TIME_PERIOD",1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"A,AL,07101010,OWNQNTFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
1,"A,AL,07101010,OWNVALFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
2,"A,AL,07101010,PQNTFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
3,"A,AL,07101010,PVALFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
4,"A,AL,07101010,QNTUNIT",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,KG,KG,KG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2171275,"A,XS,399901Z8,OWNQNTFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
2171276,"A,XS,399901Z8,OWNVALFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
2171277,"A,XS,399901Z8,PQNTFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
2171278,"A,XS,399901Z8,PVALFLAG",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:C,:C,:C
2171279,"A,XS,399901Z8,QNTUNIT",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,PST,PST,PST

In [3]:
# NOTE: Split key single column into multiple columns
index_columns = 'freq,reporter,product,indicators'.split(',')
index_columns

# NOTE: Transforming the comma separated text in cells to list of text in the same cells
# Source : 28-01-2026 - https://stackoverflow.com/questions/79118853/create-new-dataframe-rows-when-column-has-comma-delimited-values#comment139509998_79118853
# 
# NOTE: On converting the list in cells to elements of new columns
# Source : 28-01-2026 - https://stackoverflow.com/questions/35491274/split-a-pandas-column-of-lists-into-multiple-columns#35491399
new_index = pd.DataFrame(input_df['freq,reporter,product,indicators\\TIME_PERIOD'].str.split(',').tolist(), index=input_df.index, columns=index_columns)
new_index

        freq reporter   product  indicators
0          A       AL  07101010  OWNQNTFLAG
1          A       AL  07101010  OWNVALFLAG
2          A       AL  07101010    PQNTFLAG
3          A       AL  07101010    PVALFLAG
4          A       AL  07101010     QNTUNIT
...      ...      ...       ...         ...
2171275    A       XS  399901Z8  OWNQNTFLAG
2171276    A       XS  399901Z8  OWNVALFLAG
2171277    A       XS  399901Z8    PQNTFLAG
2171278    A       XS  399901Z8    PVALFLAG
2171279    A       XS  399901Z8     QNTUNIT

[2171280 rows x 4 columns]

In [4]:
new_df = input_df
# new_df = input_df.copy()

In [5]:
# NOTE: Generate MultiIndex from DataFrame
# Source : 28-01-2026 - https://pandas.pydata.org/docs/user_guide/advanced.html
new_df.index = pd.MultiIndex.from_frame(new_index)

In [7]:
columns = new_df.columns
columns

Index(['freq,reporter,product,indicators\TIME_PERIOD', '1995 ', '1996 ',
       '1997 ', '1998 ', '1999 ', '2000 ', '2001 ', '2002 ', '2003 ', '2004 ',
       '2005 ', '2006 ', '2007 ', '2008 ', '2009 ', '2010 ', '2011 ', '2012 ',
       '2013 ', '2014 ', '2015 ', '2016 ', '2017 ', '2018 ', '2019 ', '2020 ',
       '2021 ', '2022 ', '2023 ', '2024 '],
      dtype='object')

In [8]:
# NOTE: Remove space in column labels
new_df.columns = columns.map(lambda x: x.strip())

# NOTE: Remove redundant column
new_df.drop('freq,reporter,product,indicators\\TIME_PERIOD', axis=1, inplace=True)
new_df

                                  1995 1996 1997 1998 1999 2000 2001 2002  \
freq reporter product  indicators
A    AL       07101010 OWNQNTFLAG   :    :    :    :    :    :    :    :
                       OWNVALFLAG   :    :    :    :    :    :    :    :
                       PQNTFLAG     :    :    :    :    :    :    :    :
                       PVALFLAG     :    :    :    :    :    :    :    :
                       QNTUNIT      :    :    :    :    :    :    :    :
...                                ...  ...  ...  ...  ...  ...  ...  ...
     XS       399901Z8 OWNQNTFLAG   :    :    :    :    :    :    :    :
                       OWNVALFLAG   :    :    :    :    :    :    :    :
                       PQNTFLAG     :    :    :    :    :    :    :    :
                       PVALFLAG     :    :    :    :    :    :    :    :
                       QNTUNIT      :    :    :    :    :    :    :    :

                                  2003 2004  ... 2015 2016 2017 2018 2019  \
freq reporter product  indicators            ...
A    AL       07101010 OWNQNTFLAG   :    :   ...   :    :    :    :    :
                       OWNVALFLAG   :    :   ...   :    :    :    :    :
                       PQNTFLAG     :    :   ...   :    :    :    :    :
                       PVALFLAG     :    :   ...   :    :    :    :    :
                       QNTUNIT      :    :   ...   :    :    :    :    :
...                                ...  ...  ...  ...  ...  ...  ...  ...
     XS       399901Z8 OWNQNTFLAG   :    :   ...   :    :    :    :    :
                       OWNVALFLAG   :    :   ...   :    :    :    :    :
                       PQNTFLAG     :    :   ...   :    :    :    :    :
                       PVALFLAG     :    :   ...   :    :    :    :    :
                       QNTUNIT      :    :   ...   :    :    :    :    :

                                  2020 2021 2022 2023 2024
freq reporter product  indicators
A    AL       07101010 OWNQNTFLAG   :    :    :C   :C   :C
                       OWNVALFLAG   :    :    :C   :C   :C
                       PQNTFLAG     :    :    :C   :C   :C
                       PVALFLAG     :    :    :C   :C   :C
                       QNTUNIT      :    :    KG   KG   KG
...                                ...  ...  ...  ...  ...
     XS       399901Z8 OWNQNTFLAG   :    :    :C   :C   :C
                       OWNVALFLAG   :    :    :C   :C   :C
                       PQNTFLAG     :    :    :C   :C   :C
                       PVALFLAG     :    :    :C   :C   :C
                       QNTUNIT      :    :   PST  PST  PST

[2171280 rows x 30 columns]

In [9]:
# NOTE: Extracted from Eurostat using Data Browser. Access link (may be deactivated by Eurostat in the future): https://ec.europa.eu/eurostat/databrowser/view/ds-059358__custom_19869966/default/table
prodcom_classification = pd.read_excel('Prodcom_data/ds-059358__custom_19869966_spreadsheet.xlsx', sheet_name='Sheet 1', header=9, usecols='A:B', nrows=4788)
prodcom_classification

/home/nicolas/miniconda3/envs/202604-paper-1-supplementary-code/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

     PRODUCT (Codes)                                   PRODUCT (Labels)
0           07101000  Iron ores and concentrates (excluding roasted ...
1           07101010  Iron ores and concentrates. Non-agglomerated (...
2           07101020  Iron ores and concentrates. Agglomerated (excl...
3           07291100                       Copper ores and concentrates
4           07291200                       Nickel ores and concentrates
...              ...                                                ...
4783        399900Z7                                             Kaolin
4784        399900Z8  Point-of-sale terminals, ATMs and similar mach...
4785        399900Z9  Tube or pipe fittings of cast iron and cast steel
4786        399901Z0  Bismuth and articles thereof; unwrought hafniu...
4787        399901Z8  Point-of-sale terminals, ATMs and similar mach...

[4788 rows x 2 columns]

In [10]:
# NOTE: Download link: https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/codelist/ESTAT/geo?format=TSV
geo_df = pd.read_csv('Prodcom_data/ESTAT_GEO_27.0.tsv', delimiter="\t")
geo_df

                 EUR                                             Europe
0                 EU  European Union (EU6-1958, EU9-1973, EU10-1981,...
1               EU_V  European Union (aggregate changing according t...
2            EU_V_NO  European Union (aggregate changing according t...
3     EU27_2020_EFTA  European Union - 27 countries (from 2020) and ...
4     EU27_2020_IS_K  European Union - 27 countries (from 2020) and ...
...              ...                                                ...
4285             NAL                                      Not allocated
4286             NAP                                     Not applicable
4287             NRP                                        No response
4288             NSP                                      Not specified
4289             UNK                                            Unknown

[4290 rows x 2 columns]

## Prepare the subset dataframe

In [11]:
indicators = ['PRODQNT', 'EXPQNT', 'IMPQNT']

In [12]:
# NOTE: Relevant NACE codes:
# - 20.14 Other organic basic chemicals (en)
# - 20.16 Plastics in primary forms (en)
# Source : 05-02-2026 - https://showvoc.op.europa.eu/#/datasets/ESTAT_Statistical_Classification_of_Economic_Activities_in_the_European_Community_Rev._2.1._(NACE_2.1)/
NACE_codes_filter = ['2014', '2016'] 
NACE_codes_filter

['2014', '2016']

In [23]:
# NOTE: Filter the DataFrame on
# - 'freq' = 'A'
# - 'reporter' = 'EU27_2020'
# - 'product' code starts with either '2014' or '2016'
# - 'indicators' = 'PRODQNT', 'EXPQNT' or 'IMPQNT'

annual_series = new_df.loc[
    (new_df.index.get_level_values('freq') == 'A')
    & (new_df.index.get_level_values('reporter') == 'EU27_2020')
    & new_df.index.get_level_values('product').str.startswith(tuple(NACE_codes_filter))
    # & new_df.index.get_level_values('product').str.startswith(tuple(cpa_codes_filter.to_list())) # CPA codes obtained from EXIOBASE matching
    & new_df.index.get_level_values('indicators').isin(indicators)
    # & (new_df.index.get_level_values('indicators').str.endswith('QNT') | new_df.index.get_level_values('indicators').str.endswith('VAL'))
]
annual_series

                                   1995 1996 1997 1998 1999 2000 2001 2002  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :
               20141130 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
...                                 ...  ...  ...  ...  ...  ...  ...  ...
               20165965 IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :
               20165970 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :

                                          2003        2004  ...        2015  \
freq reporter  product  indicators                          ...
A    EU27_2020 20141120 EXPQNT        26356100    41433500  ...    49195700
                        IMPQNT       890151000   587529700  ...  1729281200
                        PRODQNT             :           :   ...  1167702384
               20141130 EXPQNT       183744600   117247400  ...   178548900
                        IMPQNT      1567331300  1289242200  ...  1128849700
...                                        ...         ...  ...         ...
               20165965 IMPQNT              :           :   ...          :
                        PRODQNT             :           :   ...          :
               20165970 EXPQNT        13275000    13392700  ...    13887100
                        IMPQNT        15901200    17843200  ...    22278100
                        PRODQNT             :           :   ...   168999138

                                          2016        2017        2018  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT        60905400    80848600    69913206
                        IMPQNT      1905384600  1914049400  2169914471
                        PRODQNT     1056243997   884248263   901285653
               20141130 EXPQNT       512366300   389225700   602736255
                        IMPQNT      1249475500  1326164900  1376816315
...                                        ...         ...         ...
               20165965 IMPQNT              :           :           :
                        PRODQNT             :           :           :
               20165970 EXPQNT        13663500    16053300    17265828
                        IMPQNT        24172900    27678300    25879736
                        PRODQNT      141208017   113388010   115223376

                                          2019        2020        2021  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT        94938259    77677977    81800176
                        IMPQNT      1993784447  1481110094  1698091954
                        PRODQNT      861284640   787049864  1040000000
               20141130 EXPQNT       280758738   419917128   208194049
                        IMPQNT      1418579590  1297094111   889851883
...                                        ...         ...         ...
               20165965 IMPQNT        20666257    20404112    19520791
                        PRODQNT      100000000   152008279   160000000
               20165970 EXPQNT        17426520    15447226    28596096
                        IMPQNT        31867381    32244071    34753857
                        PRODQNT      142099386   161456199   168762948

                                          2022        2023        2024
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT        74915115    58317138    65463753
                        IMPQNT      1792881362  1608889663  1707980335
                        PRODQNT      980000000   900000000   700000000
               20141130 EXPQNT       130155532    45260355     7255001
                        IMPQNT      1250333999  1035947322  1162202519
...                                        ...         ...         ...
               20165965 IMPQNT        19361212    22468842    23332447
                        PRODQNT      180000000   150000000   120000000
               20165970 EXPQNT        26284771    26982397    25391110
                        IMPQNT        36585803    32827820    42097993
                        PRODQNT      178486202   241046653    40000000

[705 rows x 30 columns]

In [24]:
unit_rows = new_df.loc[
    (new_df.index.get_level_values('freq') == 'A')
    & (new_df.index.get_level_values('reporter') == 'EU27_2020')
    & new_df.index.get_level_values('product').str.startswith(tuple(NACE_codes_filter))
    & (new_df.index.get_level_values('indicators') == 'QNTUNIT')
]
unit_rows

                                   1995 1996 1997 1998 1999 2000 2001 2002  \
freq reporter  product  indicators
A    EU27_2020 20141120 QNTUNIT      :    :    :    :    :    :    :    :
               20141130 QNTUNIT      :    :    :    :    :    :    :    :
               20141140 QNTUNIT      :    :    :    :    :    :    :    :
               20141150 QNTUNIT      :    :    :    :    :    :    :    :
               20141160 QNTUNIT      :    :    :    :    :    :    :    :
...                                 ...  ...  ...  ...  ...  ...  ...  ...
               20165950 QNTUNIT      :    :    :    :    :    :    :    :
               20165955 QNTUNIT      :    :    :    :    :    :    :    :
               20165960 QNTUNIT      :    :    :    :    :    :    :    :
               20165965 QNTUNIT      :    :    :    :    :    :    :    :
               20165970 QNTUNIT      :    :    :    :    :    :    :    :

                                   2003 2004  ... 2015 2016 2017 2018 2019  \
freq reporter  product  indicators            ...
A    EU27_2020 20141120 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   KG
               20141130 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   KG
               20141140 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   KG
               20141150 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   KG
               20141160 QNTUNIT      :    :   ...   KG   KG   KG   KG   KG
...                                 ...  ...  ...  ...  ...  ...  ...  ...
               20165950 QNTUNIT      :    :   ...   :    :    :    :    KG
               20165955 QNTUNIT      :    :   ...   :    :    :    :    KG
               20165960 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   :
               20165965 QNTUNIT      :    :   ...   :    :    :    :    KG
               20165970 QNTUNIT      KG   KG  ...   KG   KG   KG   KG   KG

                                   2020 2021 2022 2023 2024
freq reporter  product  indicators
A    EU27_2020 20141120 QNTUNIT      KG   KG   KG   KG   KG
               20141130 QNTUNIT      KG   KG   KG   KG   KG
               20141140 QNTUNIT      KG   KG   KG   KG   KG
               20141150 QNTUNIT      KG   KG   KG   KG   KG
               20141160 QNTUNIT      KG   KG   KG   KG   KG
...                                 ...  ...  ...  ...  ...
               20165950 QNTUNIT      KG   KG   KG   KG   KG
               20165955 QNTUNIT      KG   KG   KG   KG   KG
               20165960 QNTUNIT      :    :    :    :    :
               20165965 QNTUNIT      KG   KG   KG   KG   KG
               20165970 QNTUNIT      KG   KG   KG   KG   KG

[235 rows x 30 columns]

## Forecast

In [25]:
products = annual_series.index.get_level_values('product').unique()
products

Index(['20141120', '20141130', '20141140', '20141150', '20141160', '20141165',
       '20141167', '20141190', '20141213', '20141215',
       ...
       '20165670', '20165700', '20165920', '20165940', '20165945', '20165950',
       '20165955', '20165960', '20165965', '20165970'],
      dtype='object', name='product', length=235)

In [26]:
# NOTE: Estimate quantity at a certain date
# Source : 29-01-2026 - https://codepointtech.com/how-to-find-first-row-that-meets-criteria-in-pandas-effectively/

def forecast(row_series):

    row_name = row_series.name
    
    criteria = (row_series.str.strip() != ':') & row_series.str.isnumeric()

    # NOTE: Take the lastest available data index
    last_match_index = criteria.nlargest(1, keep='last').index

    matching_row = row_series.loc[last_match_index]
    value = int(matching_row.iloc[0])
    year = last_match_index[0]

    # NOTE: Retrieve unit
    unit = unit_rows.loc[(unit_rows.index.get_level_values('product') == row_name[2])].loc(axis=1)[last_match_index].iloc[0].iloc[0]

    # NOTE: Retrive product name
    # description = ''
    # description_row = prodcom_classification.loc[lambda x : x['PRODUCT (Codes)'] == row_name[2]]
    # if len(description_row):
    #     description = description_row.loc(axis=1)['PRODUCT (Labels)'].iloc[0]

    # first_match_index = criteria.idxmax()
    # Retrieve the row using .loc
    # first_matching_row = series.loc[first_match_index]

    # return series.loc[lambda x: x.str.strip() != ':'].tail(1).astype('int').values
    
    return (value, year, unit)

                                    latest value latest year latest unit
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT          65463753        2024          KG
                        IMPQNT        1707980335        2024          KG
                        PRODQNT        700000000        2024          KG
               20141130 EXPQNT           7255001        2024          KG
                        IMPQNT        1162202519        2024          KG
...                                          ...         ...         ...
               20165965 IMPQNT          23332447        2024          KG
                        PRODQNT        120000000        2024          KG
               20165970 EXPQNT          25391110        2024          KG
                        IMPQNT          42097993        2024          KG
                        PRODQNT         40000000        2024          KG

[705 rows x 3 columns]

In [39]:
pd.DataFrame(
        annual_series.apply(forecast, axis=1, result_type='expand'),
        index=annual_series.index,
        columns=['latest value', 'latest year', 'latest unit']
    )

                                    latest value  latest year  latest unit
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT               NaN          NaN          NaN
                        IMPQNT               NaN          NaN          NaN
                        PRODQNT              NaN          NaN          NaN
               20141130 EXPQNT               NaN          NaN          NaN
                        IMPQNT               NaN          NaN          NaN
...                                          ...          ...          ...
               20165965 IMPQNT               NaN          NaN          NaN
                        PRODQNT              NaN          NaN          NaN
               20165970 EXPQNT               NaN          NaN          NaN
                        IMPQNT               NaN          NaN          NaN
                        PRODQNT              NaN          NaN          NaN

[705 rows x 3 columns]

In [ ]:
latest = annual_series.apply(forecast, axis=1, result_type='expand')
latest.columns=['latest value', 'latest year', 'latest unit']

annual_series_latest = annual_series.join(latest)

# annual_series[['latest value', 'latest year', 'latest unit']] = annual_series.apply(forecast, axis=1, result_type='expand')

In [42]:
annual_series_latest

                                   1995 1996 1997 1998 1999 2000 2001 2002  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :
               20141130 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
...                                 ...  ...  ...  ...  ...  ...  ...  ...
               20165965 IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :
               20165970 EXPQNT       :    :    :    :    :    :    :    :
                        IMPQNT       :    :    :    :    :    :    :    :
                        PRODQNT      :    :    :    :    :    :    :    :

                                          2003        2004  ...        2018  \
freq reporter  product  indicators                          ...
A    EU27_2020 20141120 EXPQNT        26356100    41433500  ...    69913206
                        IMPQNT       890151000   587529700  ...  2169914471
                        PRODQNT             :           :   ...   901285653
               20141130 EXPQNT       183744600   117247400  ...   602736255
                        IMPQNT      1567331300  1289242200  ...  1376816315
...                                        ...         ...  ...         ...
               20165965 IMPQNT              :           :   ...          :
                        PRODQNT             :           :   ...          :
               20165970 EXPQNT        13275000    13392700  ...    17265828
                        IMPQNT        15901200    17843200  ...    25879736
                        PRODQNT             :           :   ...   115223376

                                          2019        2020        2021  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT        94938259    77677977    81800176
                        IMPQNT      1993784447  1481110094  1698091954
                        PRODQNT      861284640   787049864  1040000000
               20141130 EXPQNT       280758738   419917128   208194049
                        IMPQNT      1418579590  1297094111   889851883
...                                        ...         ...         ...
               20165965 IMPQNT        20666257    20404112    19520791
                        PRODQNT      100000000   152008279   160000000
               20165970 EXPQNT        17426520    15447226    28596096
                        IMPQNT        31867381    32244071    34753857
                        PRODQNT      142099386   161456199   168762948

                                          2022        2023        2024  \
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT        74915115    58317138    65463753
                        IMPQNT      1792881362  1608889663  1707980335
                        PRODQNT      980000000   900000000   700000000
               20141130 EXPQNT       130155532    45260355     7255001
                        IMPQNT      1250333999  1035947322  1162202519
...                                        ...         ...         ...
               20165965 IMPQNT        19361212    22468842    23332447
                        PRODQNT      180000000   150000000   120000000
               20165970 EXPQNT        26284771    26982397    25391110
                        IMPQNT        36585803    32827820    42097993
                        PRODQNT      178486202   241046653    40000000

                                   latest value latest year latest unit
freq reporter  product  indicators
A    EU27_2020 20141120 EXPQNT         65463753        2024          KG
                        IMPQNT       1707980335        2024          KG
                        PRODQNT       700000000        2024          KG
               20141130 EXPQNT          7255001        2024          KG
                        IMPQNT       1162202519        2024          KG
...                                         ...         ...         ...
               20165965 IMPQNT         23332447        2024          KG
                        PRODQNT       120000000        2024          KG
               20165970 EXPQNT         25391110        2024          KG
                        IMPQNT         42097993        2024          KG
                        PRODQNT        40000000        2024          KG

[705 rows x 33 columns]

In [ ]:
# NOTE: Temporary save
annual_series_latest.to_pickle('output/20260204 - annual_series.pkl')

In [ ]:
# NOTE: Temporary save
annual_series_latest.to_csv('output/20260204 - annual_series.csv')

In [ ]:
# NOTE: Load backed-up data
annual_series_latest = pd.read_pickle('output/20260130 - annual_series.pkl')

## Transform result

In [43]:
annual_series_latest.loc[annual_series_latest.index.get_level_values('indicators').isin(['PRODQNT']), 'latest value']

freq  reporter   product   indicators
A     EU27_2020  20141120  PRODQNT        700000000
                 20141130  PRODQNT       8082262489
                 20141140  PRODQNT       9154997559
                 20141150  PRODQNT       1800000000
                 20141160  PRODQNT       2043943673
                                            ...
                 20165950  PRODQNT        285515204
                 20165955  PRODQNT        140000000
                 20165960  PRODQNT        293172101
                 20165965  PRODQNT        120000000
                 20165970  PRODQNT         40000000
Name: latest value, Length: 235, dtype: int64

In [44]:
# NOTE: Generate the new MultiIndex
reorg_index = annual_series_latest.index
reorg_index = reorg_index.droplevel('indicators')
reorg_index = reorg_index.drop_duplicates()
reorg_index

MultiIndex([('A', 'EU27_2020', '20141120'),
            ('A', 'EU27_2020', '20141130'),
            ('A', 'EU27_2020', '20141140'),
            ('A', 'EU27_2020', '20141150'),
            ('A', 'EU27_2020', '20141160'),
            ('A', 'EU27_2020', '20141165'),
            ('A', 'EU27_2020', '20141167'),
            ('A', 'EU27_2020', '20141190'),
            ('A', 'EU27_2020', '20141213'),
            ('A', 'EU27_2020', '20141215'),
            ...
            ('A', 'EU27_2020', '20165670'),
            ('A', 'EU27_2020', '20165700'),
            ('A', 'EU27_2020', '20165920'),
            ('A', 'EU27_2020', '20165940'),
            ('A', 'EU27_2020', '20165945'),
            ('A', 'EU27_2020', '20165950'),
            ('A', 'EU27_2020', '20165955'),
            ('A', 'EU27_2020', '20165960'),
            ('A', 'EU27_2020', '20165965'),
            ('A', 'EU27_2020', '20165970')],
           names=['freq', 'reporter', 'product'], length=235)

In [45]:
# NOTE: Create a new DataFrame using the new MultiIndex
reorg_df = pd.DataFrame(index=reorg_index)
reorg_df

Empty DataFrame
Columns: []
Index: [(A, EU27_2020, 20141120), (A, EU27_2020, 20141130), (A, EU27_2020, 20141140), (A, EU27_2020, 20141150), (A, EU27_2020, 20141160), (A, EU27_2020, 20141165), (A, EU27_2020, 20141167), (A, EU27_2020, 20141190), (A, EU27_2020, 20141213), (A, EU27_2020, 20141215), (A, EU27_2020, 20141223), (A, EU27_2020, 20141225), (A, EU27_2020, 20141243), (A, EU27_2020, 20141245), (A, EU27_2020, 20141247), (A, EU27_2020, 20141250), (A, EU27_2020, 20141260), (A, EU27_2020, 20141270), (A, EU27_2020, 20141290), (A, EU27_2020, 20141313), (A, EU27_2020, 20141315), (A, EU27_2020, 20141323), (A, EU27_2020, 20141325), (A, EU27_2020, 20141353), (A, EU27_2020, 20141357), (A, EU27_2020, 20141371), (A, EU27_2020, 20141374), (A, EU27_2020, 20141379), (A, EU27_2020, 20141450), (A, EU27_2020, 20141470), (A, EU27_2020, 20141490), (A, EU27_2020, 20141910), (A, EU27_2020, 20141930), (A, EU27_2020, 20141950), (A, EU27_2020, 20141970), (A, EU27_2020, 20142100), (A, EU27_2020, 20142210), (A, EU27_2020, 20142220), (A, EU27_2020, 20142230), (A, EU27_2020, 20142240), (A, EU27_2020, 20142263), (A, EU27_2020, 20142265), (A, EU27_2020, 20142270), (A, EU27_2020, 20142310), (A, EU27_2020, 20142320), (A, EU27_2020, 20142333), (A, EU27_2020, 20142337), (A, EU27_2020, 20142338), (A, EU27_2020, 20142339), (A, EU27_2020, 20142350), (A, EU27_2020, 20142360), (A, EU27_2020, 20142373), (A, EU27_2020, 20142375), (A, EU27_2020, 20142410), (A, EU27_2020, 20142433), (A, EU27_2020, 20142439), (A, EU27_2020, 20142450), (A, EU27_2020, 20143120), (A, EU27_2020, 20143130), (A, EU27_2020, 20143150), (A, EU27_2020, 20143195), (A, EU27_2020, 20143197), (A, EU27_2020, 20143215), (A, EU27_2020, 20143219), (A, EU27_2020, 20143220), (A, EU27_2020, 20143230), (A, EU27_2020, 20143235), (A, EU27_2020, 20143240), (A, EU27_2020, 20143250), (A, EU27_2020, 20143271), (A, EU27_2020, 20143277), (A, EU27_2020, 20143278), (A, EU27_2020, 20143280), (A, EU27_2020, 20143310), (A, EU27_2020, 20143320), (A, EU27_2020, 20143330), (A, EU27_2020, 20143340), (A, EU27_2020, 20143350), (A, EU27_2020, 20143363), (A, EU27_2020, 20143365), (A, EU27_2020, 20143367), (A, EU27_2020, 20143370), (A, EU27_2020, 20143381), (A, EU27_2020, 20143382), (A, EU27_2020, 20143383), (A, EU27_2020, 20143385), (A, EU27_2020, 20143387), (A, EU27_2020, 20143410), (A, EU27_2020, 20143420), (A, EU27_2020, 20143430), (A, EU27_2020, 20143440), (A, EU27_2020, 20143473), (A, EU27_2020, 20143475), (A, EU27_2020, 201434Z1), (A, EU27_2020, 20144113), (A, EU27_2020, 20144119), (A, EU27_2020, 20144123), (A, EU27_2020, 20144129), (A, EU27_2020, 20144130), (A, EU27_2020, 20144151), ...]

[235 rows x 0 columns]

In [46]:
# NOTE: Get the label name of a Prodcom code
def get_label(code):
    description = ''
    description_row = prodcom_classification.loc[lambda x : x['PRODUCT (Codes)'] == code]
    if len(description_row):
        description = description_row.loc(axis=1)['PRODUCT (Labels)'].iloc[0]
    return description

In [47]:
# NOTE: Insert Prodcom product label text column
reorg_df['product label'] = ''
reorg_df['product label'] = reorg_df.apply(lambda row: get_label(row.name[2]), axis=1)
reorg_df

                                                             product label
freq reporter  product
A    EU27_2020 20141120                     Saturated acyclic hydrocarbons
               20141130                                           Ethylene
               20141140                                Propene (propylene)
               20141150              Butene (butylene) and isomers thereof
               20141160                        Buta-1,3-diene and isoprene
...                                                                    ...
               20165950  Cellulose and its chemical derivatives, in pri...
               20165955  Natural polymers and modified natural polymers...
               20165960  Natural and modified natural polymers, in prim...
               20165965  Natural polymers and modified natural polymers...
               20165970  Ion-exchangers based on synthetic or natural p...

[235 rows x 1 columns]

In [49]:
# NOTE: Return the value for a specific product key ('row_name') and for the selected indicator
def get_column_value(row_name, indicator, column_name):
    row = annual_series_latest.loc[
        (annual_series_latest.index.get_level_values('freq') == row_name[0])
        & (annual_series_latest.index.get_level_values('reporter') == row_name[1])
        & (annual_series_latest.index.get_level_values('product') == row_name[2])
        & (annual_series_latest.index.get_level_values('indicators') == indicator),
        column_name
    ]
    if len(row):
        return row.iloc[0]
    else:
        return 'N/A'

In [50]:
# NOTE: Generate 3 columns ('value', 'year', 'unit') for each indicator ('PRODQNT', 'EXPQNT', 'IMPQNT')
for indicator in indicators:
    reorg_df[indicator + ' value'] = reorg_df.apply(lambda row: get_column_value(row.name, indicator, 'latest value'), axis=1)
    reorg_df[indicator + ' year'] = reorg_df.apply(lambda row: get_column_value(row.name, indicator, 'latest year'), axis=1)
    reorg_df[indicator + ' unit'] = reorg_df.apply(lambda row: get_column_value(row.name, indicator, 'latest unit'), axis=1)
reorg_df

                                                             product label  \
freq reporter  product
A    EU27_2020 20141120                     Saturated acyclic hydrocarbons
               20141130                                           Ethylene
               20141140                                Propene (propylene)
               20141150              Butene (butylene) and isomers thereof
               20141160                        Buta-1,3-diene and isoprene
...                                                                    ...
               20165950  Cellulose and its chemical derivatives, in pri...
               20165955  Natural polymers and modified natural polymers...
               20165960  Natural and modified natural polymers, in prim...
               20165965  Natural polymers and modified natural polymers...
               20165970  Ion-exchangers based on synthetic or natural p...

                         PRODQNT value PRODQNT year PRODQNT unit  \
freq reporter  product
A    EU27_2020 20141120      700000000         2024           KG
               20141130     8082262489         2024           KG
               20141140     9154997559         2024           KG
               20141150     1800000000         2024           KG
               20141160     2043943673         2024           KG
...                                ...          ...          ...
               20165950      285515204         2024           KG
               20165955      140000000         2024           KG
               20165960      293172101         2018           KG
               20165965      120000000         2024           KG
               20165970       40000000         2024           KG

                         EXPQNT value EXPQNT year EXPQNT unit  IMPQNT value  \
freq reporter  product
A    EU27_2020 20141120      65463753        2024          KG    1707980335
               20141130       7255001        2024          KG    1162202519
               20141140     151507551        2024          KG     225368724
               20141150      91343999        2024          KG         76728
               20141160      85693377        2024          KG       5603755
...                               ...         ...         ...           ...
               20165950     181410634        2024          KG     124487250
               20165955       5738615        2024          KG       6538914
               20165960      23600475        2018          KG      25424100
               20165965      21611546        2024          KG      23332447
               20165970      25391110        2024          KG      42097993

                        IMPQNT year IMPQNT unit
freq reporter  product
A    EU27_2020 20141120        2024          KG
               20141130        2024          KG
               20141140        2024          KG
               20141150        2024          KG
               20141160        2024          KG
...                             ...         ...
               20165950        2024          KG
               20165955        2024          KG
               20165960        2018          KG
               20165965        2024          KG
               20165970        2024          KG

[235 rows x 10 columns]

In [ ]:
# NOTE: Temporary save
reorg_df.to_pickle('output/reorganized annual_series.pkl')

In [ ]:
# NOTE: Export to CSV
reorg_df.to_csv('output/reorganized annual_series.csv')